baseURL = "https://vojtamares.blog/"
languageCode = "en-us"
title = "Vojtěch Mareš - Software engineer, freelancer and stundent"
enableEmoji = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # posts per list page
  paginate = 4

[languages]
  [languages.en]
    languageName = "English"
    title = "Vojtěch Mareš - Software engineer, Freelancer, Stundent"
    subtitle = "Hello, my name is Vojtěch Mareš. I'm from Czech Republic and I am a software engineer, freelancer and for the most an university student of computer science."
    keywords = "software engineer, developer, programmer, vojtěch mareš, vojta mareš, freelancer, web developer"
    copyright = ""

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "blog"
        url = "/posts"
