baseURL = "https://vojtamares.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true

[author]
  name = "Vojtěch Mareš"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # posts per list page
  paginate = 4
  [params.links]
    [[params.links.dev]]
      identifier = "github"
      name = "github"
      url = "https://github.com/vojtamares"
    [[params.links.dev]]
      identifier = "twitter"
      name = "twitter"
      url = "https://twitter.com/vojtamares_"

[languages]
  [languages.en]
    languageName = "English"
    title = "Vojtěch Mareš - Software engineer, Freelancer, Student"
    subtitle = "Hello, my name is Vojtěch Mareš. I'm from Czech Republic and I am a software engineer, freelancer and for the most an university student of computer science."
    keywords = "software engineer, developer, programmer, vojtěch mareš, vojta mareš, freelancer, web developer"
    copyright = "Vojtěch Mareš | Everything is mine here"
    weight = 1

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog"
  [languages.cs]
    languageName = "Čeština"
    title = "Vojtěch Mareš - Softwarový indženýr na volné noze, student"
    subtitle = "Ahoj, jmenuji se Vojtěch Mareš. Jsem softwarový indženýr na volné noze (OSVČ), ale hlavně student vysoké školy kde studuji informatiku."
    keywords = "softwarový indženýr, vývojář, programátor, vojtěch mareš, vojta mareš, freelancer, osvč, na volné noze, web developer"
    copyright = "Vojtěch Mareš | Všechno tu je moje"
    weight = 2
    [[languages.cs.menu.main]]
      identifier = "home"
      name = "home"
      url = "/"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "about"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "blog"
      url = "/blog"
